### ISSUE TITLE
How to clear a text field from all tags?

### ISSUE THREAD

**Issue by rgbinnovation** [erwinheldy/tagin#1]
Hi,

Love what you have done, but how to clear a textfield from all tags?

/Bob

**Comment by erwinheldy** [comment]
You can delete all tags by using long press backspace

**Comment by rgbinnovation** [comment]
Hi Erwin, thanks for that, but that won't really work in a live production environment. You can't really have users fill out a form, and then go back and delete tags by hand after each submission (I use AJAX, meaning the form page won't reload so manual clearing would be needed).

Would you consider adding a function to clear()  a textfield that uses your tags in the near future? If not I guess I have to use another tag implementation, but I am hoping you will since it is a very basic requirement for your tags and should be part of your solution. Im sure you agree.

**Comment by erwinheldy** [comment]
For a quick fix, run the following script:

document.querySelector('#input_id').value = ''
document.querySelector('#input_id').dispatchEvent(new Event('change'))

The script above will delete the input value, then the tagin will be automatically updated
