### ISSUE TITLE
Allow for exporting tagin as a module

### ISSUE THREAD

**Issue by Teraskull** [erwinheldy/tagin#10]
## Solution:
Add `export default` to the `tagin` function:
```js
export default function tagin(el, option = {}) {
```

Import the script as a module:
```html
<script src="tagin.js" type="module"></script>
```

Then it is possible to import `tagin` inside a script:
```js
import tagin from "tagin.js";

tagin(document.querySelector('.tagin'))
```

## Reason:
This removes the current way of inline importing/using `tagin` inside HTML:
```html
<script>
    tagin(document.querySelector('.tagin'))
</script>
```
Inline JS is generally considered [bad practice](https://www.tabnine.com/blog/inline-javascript-in-html/).

## Pros:
Easier to import a required function into an existing script file, if there will useful functions in the future.

## Cons:
Internet Explorer [does not support ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) `import`. (Is that really a con though?)

**Comment by erwinheldy** [comment]
This issue was closed by the release of version 2
